import { Outfit, Rubik } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import Footer from "./components/Footer";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-outfit",
});

const rubik = Rubik({
  subsets: ["latin"],
  weight: ["300", "400", "500"],
  variable: "--font-rubik",
});

export const metadata = {
  title: "SoundSide - Find a gig near you",
  description: "Generated by SoundSide",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} ${rubik.variable} font-sans antialiased`}
      >
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
